### Numpy

In [10]:
import numpy as np

arreglo1 = np.array([1,2,3,4,5,6])
arreglo1[0]=100
arreglo2 = np.arange(7)
arreglo3 = np.arange(2,7)
arreglo4 = np.arange(2,7,0.5)

print(arreglo1)
print(arreglo2)
print(arreglo3)
print(arreglo4)
print(type(arreglo1))

[100   2   3   4   5   6]
[0 1 2 3 4 5 6]
[2 3 4 5 6]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]
<class 'numpy.ndarray'>


In [11]:
print(arreglo1[0])
print(arreglo1[[0,2]])
print(arreglo1[0:2])
print(arreglo1.size)
print(len(arreglo1))
print(arreglo1.sort())

100
[100   3]
[100   2]
6
6
None


In [12]:
arreglo5 = np.array([12,3,-3,3.2,1,0])

In [13]:
arreglo5.sort()
arreglo5

array([-3. ,  0. ,  1. ,  3. ,  3.2, 12. ])

In [14]:
#Ordenar de forma descendente
print(arreglo5[::-1])


[12.   3.2  3.   1.   0.  -3. ]


In [16]:
arreglo = np.array([1,2,3,4,5,6], dtype="i")
print(arreglo, arreglo.dtype, arreglo.itemsize)

arreglo = np.array([1000000000,2,3,4,5,6], dtype="i2")
print(arreglo, arreglo.dtype, arreglo.itemsize)

arreglo = np.array([1000000000,2,3,4,5,6], dtype="i4")
print(arreglo, arreglo.dtype, arreglo.itemsize)

arreglo = np.array([1000000000,2,3,4,5,6], dtype="i8")
print(arreglo, arreglo.dtype, arreglo.itemsize)

[1 2 3 4 5 6] int32 4
[-13824      2      3      4      5      6] int16 2
[1000000000          2          3          4          5          6] int32 4
[1000000000          2          3          4          5          6] int64 8


In [22]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.reshape((2,3)))
print(arr.reshape((3,2)))

(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [23]:
arr = np.append(arr, 7)
print(arr)

[1 2 3 4 5 6 7]


In [24]:
arr = np.insert(arr, 1, 7)
print(arr)

[1 7 2 3 4 5 6 7]


In [25]:
arr = np.delete(arr, 2)
print(arr)

[1 7 3 4 5 6 7]


In [33]:
np.where(arr==7)[0]


array([1, 6], dtype=int64)

In [35]:
# arr = [1,7,3,4,5,6,7]
print(arr+1)
print(arr*4)
print(arr*arr)

[2 8 4 5 6 7 8]
[ 4 28 12 16 20 24 28]
[ 1 49  9 16 25 36 49]


In [36]:
alturas = np.array([1.74, 1.8, 1.78, 1.68, 1.78, 1.7, 1.74, 1.74, 1.73, 1.79, 
           1.78, 1.72, 1.65, 1.78, 1.7, 1.68, 1.79, 1.68, 1.82, 1.72,
           1.75, 1.66, 1.67, 1.79, 1.75, 1.65, 1.78, 1.73, 1.71, 1.81,
           1.73, 1.71, 1.68, 1.74, 1.75, 1.68, 1.74, 1.81, 1.73, 1.82,
           1.8, 1.67, 1.73, 1.7, 1.73, 1.7, 1.81, 1.81, 1.76, 1.82, 1.68,
           1.74, 1.65, 1.8, 1.78, 1.7, 1.68, 1.78, 1.79, 1.73, 1.64, 1.67,
           1.69, 1.74, 1.76, 1.66, 1.66, 1.73, 1.79, 1.81, 1.78, 1.63,
           1.76, 1.72, 1.71, 1.7, 1.62, 1.8, 1.75, 1.8, 1.78, 1.78, 1.76,
           1.65, 1.65, 1.68, 1.74, 1.75, 1.69, 1.75, 1.7, 1.83, 1.64, 1.7,
           1.69, 1.69, 1.64, 1.69, 1.77, 1.8, 1.78, 1.69, 1.7, 1.7, 1.7,
           1.63, 1.73, 1.84, 1.66, 1.78, 1.8, 1.79, 1.78, 1.74, 1.77,
           1.73, 1.77, 1.76, 1.75, 1.8, 1.75,  1.8, 1.79, 1.71, 1.73,
           1.59, 1.76, 1.75, 1.71, 1.76, 1.8, 1.68, 1.74, 1.77, 1.73,
           1.68, 1.63, 1.67])

pesos = np.array([81.4, 88.7, 87.3, 62.7, 81.6, 80.9, 74.6, 84.7, 76.7, 88.3,
         84.6, 74, 57.7, 84.1, 79.7, 63.8, 88.4, 71.2, 87.1, 67, 80.7,
         74.7, 60.5, 85.9, 72.4, 59.7, 87.3, 85.7, 64.1, 91.9, 82.8, 75.7,
         60.2, 73.1, 74.7, 65.9, 80.9, 91.3, 76, 86.8, 80.7, 74.2, 83.1,
         77.8, 84.5, 58.8, 89.5, 87, 84, 89.9, 56.5, 80.2, 61.8, 86.3,
         82.6, 69.4, 65.8, 79.3, 88.1, 78.5, 69.1, 62.5, 74, 74.4, 87.6,
         59.6, 61.4, 83.2, 89.2, 89.2, 103.7, 67.9, 85.4, 69.5, 75.7, 
         83.9, 59.5, 87.9, 82.6, 88.1, 86.2, 88.9, 84.4, 58.4, 61.5, 69.2,
         84.2, 78, 81.1, 81.5, 74.7, 90.4, 59.2, 79.3, 65.1, 93, 60.5,
         76.4, 98.8, 89.1, 88.9, 61.1, 76.6, 86, 75.5, 66.9, 79.4, 87.9,
         72.3, 93.8, 89, 90.7, 86.7, 77.6, 85.1, 91.8, 103.2, 91.1, 67,
         86.9, 78.7, 87.1, 85.5, 69.8, 75, 53.9, 99, 93.7, 88, 79.4, 87.6,
         60.4, 82.7, 90.6, 79.8, 61.2, 62.5, 59.7])   

In [39]:
imc = pesos / (alturas*alturas)
print(imc)

#equivalente
"""
imc = []
for i in range(alturas.size):
    imc.append(pesos[i]/(alturas[i]*alturas[i]))
"""

[26.8859823  27.37654321 27.55333922 22.21513605 25.75432395 27.99307958
 24.63997886 27.97595455 25.62731799 27.55844075 26.70117409 25.01352082
 21.19375574 26.54336574 27.57785467 22.60487528 27.58965076 25.22675737
 26.29513344 22.64737696 26.35102041 27.10843373 21.69314066 26.80940046
 23.64081633 21.92837466 27.55333922 28.63443483 21.92127492 28.05164678
 27.66547496 25.88830751 21.32936508 24.14453693 24.39183673 23.3489229
 26.72083498 27.86850218 25.39343112 26.20456467 24.90740741 26.60547169
 27.76571219 26.92041522 28.23348592 20.34602076 27.3190684  26.55596594
 27.1177686  27.14044198 20.01842404 26.48962875 22.69972452 26.63580247
 26.06994066 24.01384083 23.31349206 25.0284055  27.49602072 26.22874135
 25.69155265 22.41026928 25.90945695 24.57391994 28.27995868 21.62868341
 22.28189868 27.79912459 27.83933086 27.22749611 32.72945335 25.55609921
 27.5697314  23.49242834 25.88830751 29.03114187 22.6718488  27.12962963
 26.97142857 27.19135802 27.20616084 28.05832597 27.

'\nimc = []\nfor i in range(alturas.size):\n    imc.append(pesos[i]/(alturas[i]*alturas[i]))\n'